name: test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: ./test.sh